### PR TITLE
ESR for continuous definition

### PR DESCRIPTION
**Pull request by woodbe**
Based on discussion with @gregott about a specific definition for what continuous means (that the TOE must define this)

### CODE REVIEW

**Comment by woodbe** [comment]
I'm not sure of the language here, but this is the intent anyway, that the product must define what is meant by continuous. This could be fixed (i.e. hard coded to check as a specific frequency) or dynamic (where the admin can select/adjust), either would be fine, but it must be specified to be able to test.

**Comment by gfiumara** [comment]
Apologies that I have missed most (all?) of the CMFA discussions. My concern is that if you let the vendor define _continuous_, then you can't have an apples-to-apples comparison of _continuous_ multi-factor auth. Almost seems like something that we should define -- some minimum specification for _continuous_.

**Comment by woodbe** [comment]
@gfiumara it is actually the opposite; for the ESR it is critical that this be defined so the vendor can't do whatever they want. This means we will have to create SFRs for it, which would place the bounds on what it is, and the vendor would specify what they do within those restrictions. 

The Essential Security Requirements as defined in this list are the things we actually say have to be specified and defined in the PP-Module (or cPP). So we will have to create an SFR that will set the conditions for the vendor.

**Review by gfiumara — APPROVED** [review]

**Comment by gregott** [comment]
The frequency of authentication should be dynamic depending on how “safe” the device feels.  If connected to an approved network in an approved geo-fence within the permitted times for that network and location, the device can have a higher level of trust that the user is the authorized person.  This could be a situation where the user is in his office which requires passing a guard, having a badge, knowing a PIN to enter the office and presumably being recognized by others workers in the space.  Frequency of re-authentication should be much lower than if the device is on a subway platform in the middle of the city.  I suggest the vendor be told to make the frequency dynamic and that the scheme for how to determine frequency of authentication be made known to the device administrator, and therefore the testing lab as well.  The user (admin) should be able to decide how much CMFA he wants in the various scenarios in which his device will be used.

**Comment by woodbe** [comment]
I'm going to leave this for the moment as I'm not sure if we still want this listed explicitly or are good with how it is listed in the new ESR update. I'll close once we have a full review going on from the new update.

**Comment by woodbe** [comment]
I'm going to close this based on accepting this ESR from @n-kai as better fitting with the current set.

> CMFA shall continuously determine the current level of confidence in the authentication of a user based on inputs from sensors and configuration data.

**Pull request closed without merging**
