### PR TITLE
Updates based on issues

### LINKED ISSUE #29: CMFA Resources to be protected
I am not certain about the resources to be protected list.  This is based on #28.

* The trust score that is determined by the CMFA and passed to the computer. 

I am not sure about this one. I don't know that the final score itself needs to be protected. I agree that how it is passed to the computer needs to be protected (since you wouldn't want to be able to intercept/spoof the score itself), but I am not sure about the score itself. I expect that the computer has something that says "unlock if the score is at least 75" whatever that means, and the computer would just get that score. I don't know if this needs to be protected. I think the focus should be on a trusted path (I know that is a loaded term, probably more like a protected path) to the computer authentication mechanism. Maybe something like this:

_The CMFA product must have a protected channel to present the trust score to its operating environment_

* Any personal information gathered by CMFA, such as biometric information and behavior patterns of a user.

I have several potential issues with this one. The first is whether we need to specify privacy law into a CC SFR. I'm not disputing the privacy concerns, I'm just not sure if they are anything additional to the last bullet.

* Any data used to determine the trust score including CMFA configuration data.

This one I see as fine (not sure about the phrasing, but this is fine)

### LINKED ISSUE #30: CMFA ESR set of sensors
https://github.com/biometricITC/Administration/pull/28/files#diff-0322fe0bbf26aa2800fc98c52cb2bf5bd216701bdf2d855e8467f9247b3be429R132

Should the ESR state the minimum number of sensors (I would assume 2), or provide some other expectation? I know the ESRs are fairly broad statements, but I wonder if "an adequate set of" should be "at least two". I get the point that this should be some sort of combination with at least some sensors that are "trusted" highly, but I wonder it this should be explicitly stated in the ESR.

The one issue with stating it like that is that it means that somehow we have to define (or at least provide examples) of what we mean in the document.

### LINKED ISSUE #32: Learning CMFA?
I know that we have talked about how CMFA would learn who you are (more than just checking with the sensors, but in the combination), but I am not sure that the state of the art is there yet today. This isn't explicitly stated in any ESR, but it does come out in the privacy concerns that are raised since it basically treats the entire CMFA as a biometric system. 

Do we need an ESR (which I would make optional) about this as a requirement? Ideally this is where the tech goes, but I don't know that it is there yet (for production, anyway). Today I think everything is much more about fixed points: are you on this network, in that location, connection to some device (paired together with something like face or a sensor on a watch or something). If something like gait is being used, it is likely just being reported from the biometric sensor, the CMFA doesn't know any details, and it isn't combining them to learn that you walk somewhere at specific times.

### LINKED ISSUE #33: terminology question
I was running into questions about terms to use for the trust we are placing in things. We have a trust score, trusted sensors, the authentication trust (or something like it).

I am wondering if we should change "trust score" to "confidence score/identity confidence" as this is more about the output. Then we can use trust for measuring the input (how much we trust the input) to generate confidence.

In this way we separate the terms so we aren't getting trust confused on input vs output, and confidence I think is a very accurate description of the output of CMFA.

### PR DESCRIPTION
**Pull request by woodbe**
This is to close the following:

Close #30
Close #33
Close #29

There are also some minor editorial fixes

I removed #32 from the list as there is still a question about the comment (the current proposed comment is left for placeholder).

### CODE REVIEW

**Review by n-kai — APPROVED** [review]

**Comment by gregott** [comment]
In the penultimate Note at the end of the document, we say "PAD for enrolment is unnecessary for CMFA (Some banks require PAD for biometric enrolment but I believe that accurate PAD for biometric enrolment is very difficult to achieve)."  I am hesitant to say PAD is unnecessary for CMFA.  It is not clear to me why PAD for enrollment would be any harder than PAD for verification.  Usually, enrollment is performed under better conditions than most verifications.  I would prefer to say it is optional and to use it if it is available.  A bio sensor with PAD may be more trusted than one without.  Successful verifications with PAD enabled bio sensors could result in a larger increase in the confidence level compared to a non-PAD bio sensor.

**Comment by woodbe** [comment]
@gregott I think the reason it is considered more difficult is based on who the expected use will be. For example at this point we are focused on enterprise and managed devices, but in the future it could be that the admin managing the CMFA is the end user on a personal device, not an enterprise one. The user could then enroll to their bank (for example) to use CMFA for the app (or even in the bank). But the bank doesn't necessarily have any information about the CMFA enrollment (though they may have something in accepting it only when the user can also prove their bank identity, such as the account password or their card PIN), but then the enrollment is split into a part that is in the TOE (the setting up of the CMFA itself) and then usage by the bank, that had no say whatsoever about how the user decided to let their device be configured.

If we forced PAD at enrollment, we would preclude an end user-focused scenario, but by letting it be optional, a vendor could choose whether to include it and under what circumstances.

**Review by woodbe — COMMENTED** [review]
the first comment was edited, the second one was moved to #32 for further discussion but left in the document for now as a placeholder.

**Comment by gfiumara** [comment]
@woodbe Suggest changing PAD being unnecessary (typo) to being "not required" or something like "not required, but encouraged in high-risk scenarios." If nothing else, it's less-dismissive language. While I agree with @gregott that PAD at enrollment is not _technically_ any more difficult than PAD at verification, at some point, the user has to be trusted. There **are** situations where you cannot assume that trust---for example, USG is in the process of requiring PAD when fingerprints are collected for a Federal background investigation, which are also used for enrollment---but this ESR is about unlocking a mobile device, that in a managed setting, would likely be issued after a user had undergone some other sort of trust verification. For the home user, it's moot. We're protecting against the zero/small-effort chance attack.

**Comment by woodbe** [comment]
@gfiumara that text will actually be removed from the final text (everything marked with NOTE is really more for our discussion, as opposed to the final document).

**Pull request merged**
